# Generated by Django 4.1 on 2022-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCuenta',
            fields=[
                ('id_auditoria_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('old_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
                ('old_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('old_iban', models.TextField()),
                ('new_iban', models.TextField()),
                ('old_type', models.TextField()),
                ('new_type', models.TextField()),
                ('user_action', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'auditoria_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('iban', models.TextField()),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.TextField()),
                ('hora', models.TextField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente_nombre', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('tipo_cuenta_id', models.AutoField(db_column='tipo_cuenta_Id', primary_key=True, serialize=False)),
                ('cuenta_corriente', models.IntegerField()),
                ('caja_ahorro_pesos', models.IntegerField()),
                ('caja_ahorro_dolares', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
    ]
