# Generated by Django 4.1 on 2022-08-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': True},
        ),
    ]
