# Generated by Django 4.1 on 2022-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False},
        ),
    ]
