# Generated by Django 4.1 on 2022-08-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
