# Generated by Django 4.1 on 2022-08-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False},
        ),
    ]
